//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
    using System;
    //using System.Data.Entity;
    //using System.Data.Entity.Infrastructure;
namespace GameStore.Models.Concrete
{

    
    //public partial class GamestoredbEntities : DbContext
    //{
    //    public GamestoredbEntities()
    //        : base("MySql.Data.MySqlClient;provider connection string=&quot;server=localhost;user id=root;password=Merlindex123;port=4711;database=gamestoredb&quot;")// name=GamestoredbEntities")
    //    {
    //    }
    
    //    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    //    {
    //        throw new UnintentionalCodeFirstException();
    //    }
    
    //    public DbSet<Game> games { get; set; }
    //}
}
